<a href="https://colab.research.google.com/github/xfeev/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Norma wektora, długość wektora w R^2

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

# Norma euklidesowa w R^n

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

# Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

# Odległość dwóch punktów w przestrzenii R^n

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

# Mnożenie macierzy

In [2]:
# Aby móc pomnożyć dwie macierze liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy.
# Mnożenie macierzy nie jest przemienne!

In [4]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [6]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [7]:
Z.shape

(2, 1)

In [9]:
np.dot(Y, X) # dlatego mnożenie macierzy nie jest przemienne

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [10]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [11]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

# Wyznacznik macierzy

In [13]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

# Ślad macierzy

In [14]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [15]:
# Suma wartości na przekątnej (czyli tu po prostu 2 + 3 = 5)

# Macierz jednostkowa

In [16]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Macierz odwrotna

In [27]:
A

array([[ 2,  4],
       [-1,  3]])

In [28]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [29]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [30]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

# Macierz transponowana

In [25]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [26]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

# Rozwiązywanie układów równań

In [31]:
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [32]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [33]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [34]:
X.shape

(2, 1)